import re

translations = {
    'Large aberration, lawful evil': 'Aberración grande, malvado legal',
    'Medium humanoid, any': 'Humanoide mediano, cualquiera',
    'Huge dragon, chaotic evil': 'Dragón enorme, malvado caótico',
    'Small plant, unaligned': 'Planta pequeña, sin alineamiento',
    'Large elemental, neutral': 'Elemental grande, neutral',
    'Medium beast, unaligned': 'Bestia mediana, sin alineamiento',
    'Large monstrosity, lawful neutral': 'Monstruosidad grande, neutral legal',
    'Medium construct, unaligned': 'Constructo mediano, sin alineamiento',
    'Huge giant, neutral': 'Gigante enorme, neutral',
    'Small monstrosity, unaligned': 'Monstruosidad pequeña, sin alineamiento',
    'Medium undead, chaotic evil': 'No muerto mediano, malvado caótico',
    'Medium fiend, lawful evil': 'Diablo mediano, malvado legal',
    'Tiny beast, unaligned': 'Bestia diminuta, sin alineamiento',
    'Large fiend, chaotic evil': 'Diablo grande, malvado caótico',
    'Medium humanoid, chaotic evil': 'Humanoide mediano, malvado caótico',
    'Large dragon, chaotic evil': 'Dragón grande, malvado caótico',
    'Medium fey, lawful good': 'Hada mediana, bueno legal',
    'Small beast, unaligned': 'Bestia pequeña, sin alineamiento',
    'Large beast, unaligned': 'Bestia grande, sin alineamiento',
    'Large monstrosity, unaligned': 'Monstruosidad grande, sin alineamiento',
    'Huge beast, unaligned': 'Bestia enorme, sin alineamiento',
    'Large monstrosity, chaotic evil': 'Monstruosidad grande, malvado caótico',
    'Large aberration, chaotic evil': 'Aberración grande, malvado caótico',
    'Large construct, unaligned': 'Constructo grande, sin alineamiento',
    'Large aberration, chaotic neutral': 'Aberración grande, neutral caótico',
    'Medium humanoid, neutral': 'Humanoide mediano, neutral',
    'Large monstrosity, neutral evil': 'Monstruosidad grande, malvado neutral',
    'Large fiend, lawful evil': 'Diablo grande, malvado legal',
    'Large monstrosity, neutral good': 'Monstruosidad grande, bueno neutral',
    'Huge giant, lawful evil': 'Gigante enorme, malvado legal',
    'Tiny undead, neutral evil': 'No muerto diminuto, malvado neutral',
    'Medium construct, neutral': 'Constructo mediano, neutral',
    'Small construct, unaligned': 'Constructo pequeño, sin alineamiento',
    'Huge giant, neutral evil': 'Gigante enorme, malvado neutral',
    'Medium elemental, chaotic evil': 'Elemental mediano, malvado caótico',
    'Large ooze, unaligned': 'Limo grande, sin alineamiento',
    'Medium undead, any': 'No muerto mediano, cualquiera',
    'Large beast, neutral good': 'Bestia grande, bueno neutral',
    'Medium aberration, neutral': 'Aberración mediana, neutral',
    'Small humanoid, neutral evil': 'Humanoide pequeño, malvado neutral',
    'Medium dragon, chaotic evil': 'Dragón mediano, malvado caótico',
    'Medium monstrosity, unaligned': 'Monstruosidad mediana, sin alineamiento',
    'Medium fey, neutral evil': 'Hada mediana, malvado neutral',
    'Medium monstrosity, neutral': 'Monstruosidad mediana, neutral',
    'Large monstrosity, lawful good': 'Monstruosidad grande, bueno legal',
    'Medium monstrosity, chaotic evil': 'Monstruosidad mediana, malvado caótico',
    'Huge giant, chaotic evil': 'Gigante enorme, malvado caótico',
    'Medium humanoid, lawful evil': 'Humanoide mediano, malvado legal',
    'Tiny construct, neutral': 'Constructo diminuto, neutral',
    'Huge monstrosity, unaligned': 'Monstruosidad enorme, sin alineamiento',
    'Small elemental, neutral evil': 'Elemental pequeño, malvado neutral',
    'Tiny fiend, lawful evil': 'Diablo diminuto, malvado legal',
    'Medium elemental, neutral': 'Elemental mediano, neutral',
    'Small humanoid, lawful evil': 'Humanoide pequeño, malvado legal',
    'Gargantuan monstrosity, chaotic evil': 'Monstruosidad gigantesca, malvado caótico',
    'Medium undead, any evil alignment': 'No muerto mediano, cualquier alineamiento malvado',
    'Small elemental, chaotic neutral': 'Elemental pequeño, neutral caótico',
    'Large monstrosity, lawful evil': 'Monstruosidad grande, malvado legal',
    'Medium monstrosity, lawful evil': 'Monstruosidad mediana, malvado legal',
    'Large undead, lawful evil': 'No muerto grande, malvado legal',
    'Medium undead, lawful evil': 'No muerto mediano, malvado legal',
    'Medium fiend, neutral evil': 'Diablo mediano, malvado neutral',
    'Large fiend, neutral evil': 'Diablo grande, malvado neutral',
    'Medium aberration, neutral evil': 'Aberración mediana, malvado neutral',
    'Large giant, chaotic evil': 'Gigante grande, malvado caótico',
    'Large undead, neutral evil': 'No muerto grande, malvado neutral',
    'Large giant, lawful evil': 'Gigante grande, malvado legal',
    'Large aberration, neutral': 'Aberración grande, neutral',
    'Large celestial, chaotic good': 'Celestial grande, bueno caótico',
    'Large celestial, lawful good': 'Celestial grande, bueno legal',
    'Large elemental, neutral evil': 'Elemental grande, malvado neutral',
    'Medium fey, chaotic neutral': 'Hada mediana, neutral caótico',
    'Medium fey, chaotic evil': 'Hada mediana, malvado caótico',
    'Large plant, unaligned': 'Planta grande, sin alineamiento',
    'Medium plant, unaligned': 'Planta mediana, sin alineamiento',
    'Medium aberration, lawful neutral': 'Aberración mediana, neutral legal',
    'Tiny fey, neutral good': 'Hada diminuta, bueno neutral',
    'Huge giant, chaotic good': 'Gigante enorme, bueno caótico',
    'Gargantuan monstrosity, unaligned': 'Monstruosidad gigantesca, sin alineamiento',
    'Huge plant, chaotic good': 'Planta enorme, bueno caótico',
    'Small plant, neutral evil': 'Planta pequeña, malvado neutral',
    'Medium humanoid, neutral good': 'Humanoide mediano, bueno neutral',
    'Medium humanoid, neutral evil': 'Humanoide mediano, malvado neutral',
    'Tiny undead, chaotic evil': 'No muerto diminuto, malvado caótico',
    'Large dragon, unaligned': 'Dragón grande, sin alineamiento'
}

with open('monsters.json', 'r', encoding='utf-8') as f:
    content = f.read()

for old, new in translations.items():
    content = content.replace(old, new)

with open('monsters.json', 'w', encoding='utf-8') as f:
    f.write(content)

print("Traducciones aplicadas exitosamente.")